import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Natours | Exciting tours for adventurous people",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="stylesheet" href="css/icon-font.css" />
        <link rel="stylesheet" href="css/style.css" />
        <link
          rel="shortcut icon"
          type="image/png"
          href="public/img/favicon.png"
        />

        <title>Natours | Exciting tours for adventurous people</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
